name: Deploy

on:
  push:
    branches:
      - main #Your github branch name

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: akhileshns/heroku-deploy@v3.12.12 # This is the action
        with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY}} # Go to settings -> Secrets -> Actions and crete a New repository secret named HEROKU_API_KEY and as the value enter your heroku api key (You can obtain it from heroku settings)
          heroku_app_name: "bla-blar" #Your heroku app name
          heroku_email: "myemail@gmail.com" #Your heroku app name
          branch: "main" #Your github branch name
          docker_heroku_process_type: "worker"
